require_relative '../node_modules/react-native-test-app/test_app'

use_flipper!

workspace 'fabricexample.xcworkspace'

use_test_app! :fabric_enabled => true, :turbomodule_enabled => true, :hermes_enabled => true
