name: Windows CI
on: [pull_request]

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: 16.5

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Check node modules cache
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install node modules
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --pure-lockfile

    - name: Install example node modules
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: cd example && yarn

    - name: Build Windows
      run: cd example && yarn build:windows

    - name: Generate Windows App
      run: cd example && npx install-windows-test-app --use-nuget
     
    # - name: Start Appium server
    #   shell: powershell
    #   run: Start-Process PowerShell -ArgumentList "yarn appium"
      
    # - name: Run tests
    #   run: yarn test:windows
